### ISSUE TITLE
Wii U titles on USB don't appear if there is a second HDD with uStealth present for vWii

### ISSUE THREAD

**Issue by grockk** [Xpl0itU/savemii#13]
Savemii doesn't detect any titles on Wii U HDD if I have a uStealth hidden drive plugged in for USBLoader GX. I just have to remove it to make backups so it's not the end of the world but it'd be nice if it checked additional USB drives for Wii U format or somehow skipped the uStealth drive.

**Comment by Xpl0itU** [comment]
Fixed in 1.4.8
