### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by LittleFIve233** [Xpl0itU/savemii#21]
![IMG_20221030_202159](https://user-images.githubusercontent.com/68946023/198878226-5fd41872-ddcb-4718-a84c-8afad42c88f5.jpg)

I set it to Simplified Chinese, But the content to the right of "Sort" is in Japanese. 
And this console is the Japanese version

**Comment by Xpl0itU** [comment]
That is indeed a bug that is fixed in the refactor branch, will be fixed on the next version, so don’t worry, it will come out soon

**Comment by LittleFIve233** [comment]
![IMG_20221030_203006](https://user-images.githubusercontent.com/68946023/198878551-08288490-cde7-4907-8902-dbd6b227b5e0.jpg)
Oh, Don't forget this.

**Comment by Xpl0itU** [comment]
The banner.bin or what?

**Comment by LittleFIve233** [comment]
> The banner.bin or what?

The text behind Banner.bin is in Japanese

**Comment by Xpl0itU** [comment]
Could you try this and see if it fixes it? [https://github.com/Xpl0itU/savemii/actions/runs/3355500566](https://github.com/Xpl0itU/savemii/actions/runs/3355500566)

**Comment by LittleFIve233** [comment]
> Could you try this and see if it fixes it? https://github.com/Xpl0itU/savemii/actions/runs/3355500566

I tried Aroma, but after selecting language and pressing A Button it gets stuck

Here is the video
https://user-images.githubusercontent.com/68946023/198879806-4a7ed98a-b338-49c4-b54a-5aafc35e8ec3.mp4

**Comment by Xpl0itU** [comment]
Been struggling the whole day to get the Wii U titles to reload too but I decided to give up, try this build, it fixed it on my end [https://github.com/Xpl0itU/savemii/actions/runs/3356381209](https://github.com/Xpl0itU/savemii/actions/runs/3356381209)

**Comment by LittleFIve233** [comment]
I tried 1.5.0-Aroma, it can't load vwii titles

1.4.9: 
![040F3DE8C7D0BED52FB2E8F2DDFB5F76](https://user-images.githubusercontent.com/68946023/199036538-695f2d33-3126-4c22-8595-6f29e4c7674c.jpg)
1.5.0: 
![38FA252B0E5B88E8D6B8CC9BE374F3D9](https://user-images.githubusercontent.com/68946023/199036585-cf82dc18-c261-4faa-9157-ab889e042a7e.jpg)

**Comment by Xpl0itU** [comment]
It works for me, try updating your aroma

**Comment by LittleFIve233** [comment]
> It works for me, try updating your aroma

I tried AromaB6 but it's still. 
I will try other Consoles.

**Comment by Xpl0itU** [comment]
>  I will try other Consoles.

Please do, as I already said, it works perfectly fine on mine

**Comment by Xpl0itU** [comment]
Figured out what was wrong, download 1.5.1 and try again, this time vWii should load just fine

**Comment by LittleFIve233** [comment]
> Figured out what was wrong, download 1.5.1 and try again, this time vWii should load just fine

Nice job! All functions are ok!
