### ISSUE TITLE
"initFS failed" issue

### ISSUE THREAD

**Issue by HEYimHeroic** [Xpl0itU/savemii#25]
the error i'm getting is this:
![Untitled](https://user-images.githubusercontent.com/48461034/207754771-689c3ad2-353b-46cd-ad2b-aaabddd7686c.png)

of course, after seeing this, i went and updated Mocha CFW and tried again, but i still got the same issue.

granted, i modded my Wii U a long time ago (back when you still needed to buy a DS game to mod it) and i haven't re-modded my Wii U because i have absolutely no idea how to go about upgrading from the old modding methods. but still, this should still work, right? it worked before and i used it all the time, so i don't know what changed to make it stop working...

**Comment by Xpl0itU** [comment]
Follow wiiu.hacks.guide to upgrade to tiramisu, it is required to use SaveMii WUT Port

**Comment by eadmaster** [comment]
as alternative i've found [this homebrew which also have a save backup feature and does not require tiramisu](https://github.com/emiyl/dumpling).
