### ISSUE TITLE
Immediate hangs trying to write on 1.5.4

### ISSUE THREAD

**Issue by jmakin-godaddy** [Xpl0itU/savemii#28]
I have tried to use 1.5.4 to backup saves, I think I may have been able to just one but after that any attempt immediately hung as if I hadn't pressed anything but now unable to cleanly exit, and having to hard power off the console.

I went back to 1.5.3 and had no problems.

This was in aroma environment

**Comment by Xpl0itU** [comment]
Could you try this build? [https://github.com/Xpl0itU/savemii/actions/runs/3938246430](https://github.com/Xpl0itU/savemii/actions/runs/3938246430)

**Comment by Xpl0itU** [comment]
Fixed on 1.5.5
