### ISSUE TITLE
All slots are empty

### ISSUE THREAD

**Issue by mikesk8** [Xpl0itU/savemii#36]
Hello, I have just installed your latest version 1.5.8 and wanted to backup individual saves from WiiU games. However, I have noticed that all the slots state <empty>. I went through all 256. The other option is all users. I am not sure if this is my setup or issue with this version. 

Previously, I was using 1.5.3 and I could see no empty slots. 

Could you please help? 
Thank you! m.

**Comment by Xpl0itU** [comment]
Yeah if the slots are empty it means that you can backup to those
