### ISSUE TITLE
[Bug] SaveMii WUT opens black screen when USB drive connected

### ISSUE THREAD

**Issue by chrisonhub** [Xpl0itU/savemii#43]
EU console running 5.5.5 and fresh wiihacks guide Tiramisu instructions followed.   1.5.9 SaveMii WUT installed from homebrew app store or downloaded direct from github to SD card give same result.  Have to hard reset main console to recover.
App runs as expected without the USB drive attached.

**Comment by clintonb** [comment]
This remains an issue for Aroma version 1.6.1. This makes it impossible to backup a save from an external drive.

**Comment by w3irDv** [comment]
@chrisonhub , @clintonb , the new release https://github.com/Xpl0itU/savemii/releases/tag/1.6.3 should fix this problem. If it's not the case, please report it.

**Comment by clintonb** [comment]
This worked. Thanks!

**Comment by chrisonhub** [comment]
Confirmed, worked for me too.  Many thanks.

**Comment by themaninthewalls-him** [comment]
@w3irDv this didnt work for me and I'm having the same issues. What should I do? everything is up to date.
