### ISSUE TITLE
[Bug] After exiting the app on Aroma, the Home menu sometimes doesn't come up, forcing me to hard restart...

### ISSUE THREAD

**Issue by PlayerGameSK** [Xpl0itU/savemii#44]
Essentially whenever I try quitting out of the app on Aroma, sometimes (feels like more often than not recently) it'll get stuck on a pink screen (see below) without actually opening the Home menu like it's supposed to, effectively "softlocking" the console and forcing me to restart it... this is really annoying since I use the app pretty often :/ 

![image](https://github.com/Xpl0itU/savemii/assets/13349715/87ca3a67-01e6-4a0e-bd5e-cbb8644924b2)

**Comment by w3irDv** [comment]
Ho @PlayerGameSK , the new release https://github.com/Xpl0itU/savemii/releases/tag/1.6.3 solves this problem.
