### ISSUE TITLE
[Bug] after updating to 1.6.0 HBL saves are not visible in the app

### ISSUE THREAD

**Issue by mikesk8** [Xpl0itU/savemii#48]
Hi, 

I have just updated from 1.5.9 to 1.6.0 HBL version. However, after the update the app does not see any of the backups on the SD. All the backup slots are empty. Is it supposed to work like this and you need to recreate all saves?

Thank you, m.

**Comment by jan-hofmeier** [comment]
PR #49 fixes this, it should then be in the 1.6.1 release.

You can find a build with that patch here: https://github.com/Xpl0itU/savemii/actions/runs/8494444568?pr=49

**Comment by mikesk8** [comment]
Thank you! I will check it once at home today and will report back ;-)

**Comment by Xpl0itU** [comment]
Should be fixed in 1.6.1

**Comment by mikesk8** [comment]
It works well; I have tested it. Thank you!
