### ISSUE TITLE
Wii u freezes when I press ‘a’ on “wii u save management”

### ISSUE THREAD

**Issue by qlowquest** [Xpl0itU/savemii#50]
Everytime I run savemii, i am able to access vwii save management and batch backup, but whenever i click on “wii u save management” my wii u freezes. Is there a way to stop this from always happening? I’ve searched everywhere and there are barely people out there with this problem, and when they have this problem people don’t seem to have solutions for it.

**Comment by w3irDv** [comment]
@qlowquest , can you try the new release https://github.com/Xpl0itU/savemii/releases/tag/1.6.3? If you have still this problem, please report it back.

**Comment by w3irDv** [comment]
Please reopen it if 1.6.3 still freezes.

**Comment by zyonse** [comment]
Having this issue on 1.6.3 but ejecting the game disc fixed it

**Comment by w3irDv** [comment]
Thanks for the feedback. This freeze when a disc is in the drive will be
fixed in the next release (october).
