### ISSUE TITLE
Some saves not being recognized by SaveMii

### ISSUE THREAD

**Issue by mr-blackmore** [Xpl0itU/savemii#51]
I've been transferring saves from my old account to my new account on the same console. However, SaveMii doesn't recognize my save of Yoshi's Wolly World from my old account and refuses to back it up. It's so far the only game that I couldn't back up. Any reason for this?

**Comment by w3irDv** [comment]
Hi @mr-blackmore , can you try this: https://github.com/Xpl0itU/savemii/releases/tag/1.6.3? It should fix your issue. The previous version had some problems for detecting common saves, and  yoshi's seems to fit in the case. It has no user specific data, and only one common save file. With the new version I have had no problem to back up its saves.
