### ISSUE TITLE
Timestamps appear to be broken after the latest update (1.6.1)

### ISSUE THREAD

**Issue by PlayerGameSK** [Xpl0itU/savemii#54]
What the title says, after updating to the latest version, every timestamp just shows "Date: " with no actual date showing up after that, and it doesn't seem like the "savemiiMeta.json" files are getting updated either...

**Comment by w3irDv** [comment]
Hi @PlayerGameSK , solved with the 1.6.3, for new backups or for backups generated with v1.5.9 or below. As you have pointed out, the savemiiiMeta.json was lost in the 1.6.0 releae, so there is no way to show timestamps for v1.6.0 or v1.6.1 backups.
