### ISSUE TITLE
"backup failed" happening with every game

### ISSUE THREAD

**Issue by DanHolli** [Xpl0itU/savemii#55]
Exactly what the title says, restarted, re-downloaded and everything 
V1.6.1
aroma base 0.1.3 (2023-07-31)

**Comment by w3irDv** [comment]
Hi @DanHolli , are you still  having this issue? Can you try the new release https://github.com/Xpl0itU/savemii/releases/tag/1.6.3 to see if there is any improvement? if not, how are you  backing up your games? With the allusers option? Only one specific user and/or common saves? Can you provide the name of one of the titles for which you cannot backup save games?

**Comment by w3irDv** [comment]
Please reopen it if 1.6.3 still fails,
