### ISSUE TITLE
savemii freezes if i press the home button

### ISSUE THREAD

**Issue by Bobsmilk** [Xpl0itU/savemii#58]
everytime i press the home button savemii freezes i got the virsion off the homebrew shop and tried redownloading it to see if thatd fix it which it didnt so i tried from here version 1.6.1 but im still having the issue

**Comment by w3irDv** [comment]
Hi! Can you build the application by yourself? This [PR](https://github.com/Xpl0itU/savemii/pull/59) should fix your issue

**Comment by w3irDv** [comment]
Ho @Bobsmilk , the new release https://github.com/Xpl0itU/savemii/releases/tag/1.6.3 fix this problem.
