### ISSUE TITLE
SChinese.json updated.

### ISSUE THREAD

**Issue by kavid** [Xpl0itU/savemii#62]
SChinese.json updated.
[SChinese.zip](https://github.com/user-attachments/files/16738757/SChinese.zip)

**Comment by w3irDv** [comment]
Thanks, it will go into the next release. If it's ok with you, I'll contact beforehand to see if you can help with (probable) new translations.

**Comment by w3irDv** [comment]
Translation added. Can be previewed in this interim build: https://github.com/Xpl0itU/savemii/actions/runs/10586515866.

**Comment by w3irDv** [comment]
Hi @kavid,

Here you can find the source for the new savemii version: https://github.com/w3irDv/savemii/tree/enh/mngslot. If you are still interested, I will appreciate if you could translate all the new menus. The json file contains already the new keys, so only the translation parts is missing.

New binaries can be found here: https://github.com/Xpl0itU/savemii/actions/runs/12549246003.
